# Generated by Django 4.2 on 2025-07-07 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tracker", "0004_budget_budget_unique_budget_per_category_month"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="budget",
            name="unique_budget_per_category_month",
        ),
    ]
